dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
  chrome: stable
branches:
  only:
  - master
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- wget "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
- tar xfz geckodriver-v0.24.0-linux64.tar.gz
- sudo mv geckodriver /usr/local/bin
- export DISPLAY=:99.0
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- wget -N http://chromedriver.storage.googleapis.com/87.0.4280.87/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install selenium
- pip install webdriver-manager
script:
- cd decide
- sudo apt-get install firefox
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test authentication visualizer voting
  --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
notifications:
  email:
    recipients:
    - moimarram@alum.us.es
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  app: prueba-xamen
  strategy: git
  api_key:
    secure: 1L7NR7Y0lhz8Vsta7Otl+tzBJKQvWBHPEp+3iSs5w/M6ciu+TohjqKsJtkK1NJFjDnV0jLiAbvRsQCNnkE0UVlFrcPcEu2HBx0crpaGM1nS3KZ82d1fbKXyPIatnG/6hKowpqD4GVi0IXxkPZCKNgZVk7UeP452nPbt17zh1Q7F7E6Uwj/td2cwicYhpX8Ve2VYI+pcrEEkZbLp0n7WEmgAffMSZxfPuzyXuQsaFgdw3LR47MbUXSr1+T52McdnHGBBcixyDh1SMbeZXTKDsYz+quj6xbtEYcrxGXfGE0doQczv6wRj2tZnDVBvrP5yfo0GmLgIFoLoA6MBMseoRDgStq60lr326PN/RwuXGQ2MeJNv4KjJnnQiZxPlFCW9aGVCYk2OI6HHvHq16oq7KVCu4/DbLnDTsguAtbllfh6Stqd5GHEYOrQI9jaZuk4vLvH3kz/sTrQ0Oi5EPzrpI4BDvgciUkpXhmLU2j1/HJ0eIsQJvZbHXg9BkNIxszeC6qCt23avGck0KEPIYF+ATYpelPC8wSCccmRwkMhnUBIaT9UbfToM7MEYiVYDY20T5U8ykVWTOY2mZYVXrCy/djEd8KqqfW3XQcy6el4MbpHU2ycIdCpjAqXw+QQhaBd1KRUAtuPmbXJeYCL/xtOy0fRfpTa5lkUkSawBH0znxxyo=
